CREATE DATABASE IF NOT EXISTS `dofus` CHARACTER SET utf8 COLLATE utf8_general_ci;

USE dofus;

CREATE TABLE  `users` (
`id` INT AUTO_INCREMENT PRIMARY KEY ,
`lastname` VARCHAR( 100 ) NOT NULL ,
`firstname` VARCHAR( 100 ) NOT NULL ,
`email` VARCHAR( 100 ) NOT NULL ,
`password` VARCHAR( 100 ) NOT NULL,
`status` VARCHAR( 100 ) NOT NULL
) ENGINE = INNODB;